package com.aaditya.banking.service.enums;

import com.fasterxml.jackson.annotation.JsonValue;

public enum State {

  DELHI("DELHI"), PUNJAB("PUNJAB"), RAJASTHAN("RAJASTHAN"), TAMIL_NADU("TAMIL_NADU"), TELANGANA(
      "TELANGANA"), UTTAR_PRADESH("UTTAR_PRADESH"), UTTARAKHAND("UTTARAKHAND"), WEST_BENGAL(
      "WEST_BENGAL"), CHANDIGARH("CHANDIGARH"), DADRA_AND_NAGAR_HAVELI(
      "DADRA_AND_NAGAR_HAVELI"), DAMAN_AND_DIU("DAMAN_AND_DIU"), LAKSHADWEEP(
      "LAKSHADWEEP"), PUDUCHERRY("PUDUCHERRY"), ANDAMAN_AND_NICOBAR_ISLANDS(
      "ANDAMAN_AND_NICOBAR_ISLANDS"), ANDHRA_PRADESH("ANDHRA_PRADESH"), ARUNACHAL_PRADESH(
      "ARUNACHAL_PRADESH"), ASSAM("ASSAM"), BIHAR("BIHAR"), CHHATTISGARH("CHHATTISGARH"), GOA(
      "GOA"), GUJARAT("GUJARAT"), HARYANA("HARYANA"), HIMACHAL_PRADESH(
      "HIMACHAL_PRADESH"), JAMMU_AND_KASHMIR("JAMMU_AND_KASHMIR"), JHARKHAND(
      "JHARKHAND"), KARNATAKA("KARNATAKA"), KERALA("KERALA"), MADHYA_PRADESH(
      "MADHYA_PRADESH"), MAHARASHTRA("MAHARASHTRA");

  private final String value;

  private State(final String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }
}
